authentication:
  key: examplesecret
  password:
    day: daypass
    evening: eveningpass
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding
    username: postgres
    password: password
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl